name: 'Simple Unity CI'
description: 'Build a Unity project with SimpleUnityCI'
inputs:
  build_server:
    description: 'URL of your build server'
    required: true

  git_repo:
    description: ''
    required: true
  branch:
    description: ''
    required: true
  build_target:
    description: ''
    required: true
  keystore_name:
    description: ''
    required: false
  keystore_pass:
    description: ''
    required: false
  keyalias_name:
    description: ''
    required: false
  keyalias_pass:
    description: ''
    required: false
  oculus_app_id:
    description: ''
    required: false
  oculus_app_secret:
    description: ''
    required: false
  oculus_release_channel:
    description: ''
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'

